// client/src/components/notes/NoteCard.tsx
import { Note } from '../../models/Note';

interface NoteCardProps {
  note: Note;
  showExtraContent?: boolean;
  onClickHandler: (note: Note) => void;
}

export default function NoteCard({
  note,
  showExtraContent,
  onClickHandler,
}: NoteCardProps) {
  return (
    <div
      className="mx-auto py-2 text-left border-2 rounded pl-2 my-4 hover:cursor-pointer truncate"
      onClick={() => onClickHandler(note)}
    >
      <p className="font-bold">{note.title}</p>
      {showExtraContent && (
        <div className="flex gap-2 truncate">
          <p>{note.editionDate.toDateString()}</p>
          <p>{note.content}</p>
        </div>
      )}
    </div>
  );
}

// client/src/components/notes/NoteCard.vue
<script setup lang="ts">
import { PropType } from 'vue';
import { Note } from '../../models/Note';
defineProps({
  note: {
    type: Object as PropType<Note>,
    required: true,
  },
  showExtraContent: {
    type: Boolean,
    default: false,
  },
});
</script>

<template>
  <div
    class="mx-auto py-2 text-left border-2 rounded pl-2 my-4 hover:cursor-pointer truncate"
    @click="$router.push({ name: 'NoteEdit', params: { id: note.id } })"
  >
    <p class="font-bold">{{ note.title }}</p>
    <template v-if="showExtraContent">
      <div class="flex gap-2">
        <p>{{ note.editionDate.toDateString() }}</p>
        <p>{{ note.content }}</p>
      </div>
    </template>
  </div>
</template>
