// client/src/components/layout/NavBar.tsx
import { NavLink } from 'react-router-dom';
import { links } from '../../data';

export default function NavBar() {
  const isMobile = screen.width <= 760;

  return (
    <>
      {isMobile && (
        <section className="w-full bg-slate-400 text-center flex justify-evenly pt-4 pb-10 lg:pb-4">
          {links.map((link) => (
            <NavLink
              key={link.name}
              to={link.route}
              className={({ isActive }) =>
                'font-bold text-xl my-auto ' +
                (isActive ? 'text-white bg-slate-800 p-2 rounded' : '')
              }
            >
              {link.name}
            </NavLink>
          ))}
        </section>
      )}
    </>
  );
}

// client/src/components/layout/NavBar.vue
<script setup lang="ts">
const isMobile: boolean = screen.width <= 760;
</script>

<template>
  <template v-if="isMobile">
    <section class="w-full bg-slate-400 text-center flex justify-center py-4">
      <a href="/" class="font-bold text-xl my-auto">Family Management</a>
    </section>
  </template>
  <template v-else>
    <section class="w-full bg-slate-400 text-center flex justify-center py-4">
      <p class="font-bold text-xl my-auto">Family Management</p>
    </section>
  </template>
</template>
